{{- if .Values.contactList -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-files
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  contacts.csv: |
    name,number
    {{- .Values.contactList | nindent 4 }}
{{- end }}
